=== dandiodati/SOA/src/com/nightfire/framework/test/msg_api_test.dtd
<!ELEMENT specialaccess (asr|sa|aci)* >
<!ELEMENT asr (asr_adminsection|asr_billsection|asr_contactsection)* >
<!ELEMENT asr_adminsection (CCNA|PON|ICSC|DTSENT|DDD|REQTYP|BAN|BIC_TEL)* >
<!ELEMENT CCNA EMPTY >
 <!ATTLIST CCNA value CDATA #IMPLIED>
<!ELEMENT PON EMPTY >
 <!ATTLIST PON value CDATA #IMPLIED>
<!ELEMENT ICSC EMPTY >
 <!ATTLIST ICSC value CDATA #IMPLIED>
<!ELEMENT DTSENT (DATE|TIME)* >
<!ATTLIST DTSENT type CDATA #IMPLIED>
<!ELEMENT DATE EMPTY >
 <!ATTLIST DATE value CDATA #IMPLIED>
<!ELEMENT TIME EMPTY >
 <!ATTLIST TIME value CDATA #IMPLIED>
<!ELEMENT DDD EMPTY >
 <!ATTLIST DDD value CDATA #IMPLIED>
<!ELEMENT REQTYP (CHAR)* >
<!ATTLIST REQTYP type CDATA #IMPLIED>
<!ATTLIST REQTYP value CDATA #IMPLIED>
<!ELEMENT CHAR EMPTY >
 <!ATTLIST CHAR value CDATA #IMPLIED>
<!ELEMENT BAN EMPTY >
 <!ATTLIST BAN value CDATA #IMPLIED>
<!ELEMENT BIC_TEL (AREA|EXCH|NUMBER)* >
<!ATTLIST BIC_TEL type CDATA #IMPLIED>
<!ELEMENT AREA EMPTY >
 <!ATTLIST AREA value CDATA #IMPLIED>
<!ELEMENT EXCH EMPTY >
 <!ATTLIST EXCH value CDATA #IMPLIED>
<!ELEMENT NUMBER EMPTY >
 <!ATTLIST NUMBER value CDATA #IMPLIED>
<!ELEMENT asr_billsection (BILLNM)* >
<!ELEMENT BILLNM EMPTY >
 <!ATTLIST BILLNM value CDATA #IMPLIED>
<!ELEMENT asr_contactsection (INIT|INIT_TEL_NO|INIT_STREET|INIT_STATE|INIT_ZIP_CODE|DTREC)* >
<!ELEMENT INIT EMPTY >
 <!ATTLIST INIT value CDATA #IMPLIED>
<!ELEMENT INIT_TEL_NO (AREA|EXCH|NUMBER)* >
<!ATTLIST INIT_TEL_NO type CDATA #IMPLIED>
<!ELEMENT INIT_STREET EMPTY >
 <!ATTLIST INIT_STREET value CDATA #IMPLIED>
<!ELEMENT INIT_STATE EMPTY >
 <!ATTLIST INIT_STATE value CDATA #IMPLIED>
<!ELEMENT INIT_ZIP_CODE EMPTY >
 <!ATTLIST INIT_ZIP_CODE value CDATA #IMPLIED>
<!ELEMENT DTREC (DATE|TIME)* >
<!ATTLIST DTREC type CDATA #IMPLIED>
<!ELEMENT sa (adminsection|sa_circuitdetail|sa_location|remarks)* >
<!ELEMENT adminsection (CCNA|PON|ASR_NO)* >
<!ELEMENT ASR_NO EMPTY >
 <!ATTLIST ASR_NO value CDATA #IMPLIED>
<!ELEMENT sa_circuitdetail (SECTLV)* >
<!ELEMENT SECTLV (SECTION)* >
<!ATTLIST SECTLV type CDATA #IMPLIED>
<!ELEMENT SECTION EMPTY >
 <!ATTLIST SECTION value CDATA #IMPLIED>
<!ELEMENT sa_location EMPTY >
 <!ELEMENT remarks (REMARKS)* >
<!ELEMENT REMARKS EMPTY >
 <!ATTLIST REMARKS value CDATA #IMPLIED>
<!ELEMENT aci (adminsection|aci_circuitdetail)* >
<!ELEMENT aci_circuitdetail (CKR)* >
<!ELEMENT CKR EMPTY >
 <!ATTLIST CKR value CDATA #IMPLIED>

=== dandiodati/SOA/src/com/nightfire/framework/test/msg_api_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE specialaccess SYSTEM "file:./msg_api_test.dtd">

<specialaccess>

<asr>
    <asr_adminsection>
		<CCNA value="fubar"/>
		<PON value="asf123454"/>
		<ICSC value="PT02"/>
		<DTSENT type="datetime">
			<DATE value="12-12-1998"/>
			<TIME value="11:15 PM"/>
		</DTSENT>
		<DDD value="03-22-1996"/>
		<REQTYP type="complex" value="SA">
			<CHAR value="S"/>
			<CHAR value="A"/>
		</REQTYP>
		<BAN value="1234978"/>
		<BIC_TEL type="phoneno">
			<AREA value="617"/>
			<EXCH value="555"/>
			<NUMBER value="1234"/>
		</BIC_TEL>
    </asr_adminsection>
    <asr_billsection>
		<BILLNM value="Fred Bloggs"/>
    </asr_billsection>
    <asr_contactsection>
		<INIT value="Wade Boggs"/>
		<INIT_TEL_NO type="phoneno">
			<AREA value="617"/>
			<EXCH value="555"/>
			<NUMBER value="1234"/>
		</INIT_TEL_NO>
		<INIT_STREET value="123 Heaven's Gate"/>
		<INIT_STATE value="CA"/>
		<INIT_ZIP_CODE value="97867"/>
		<DTREC type="datetime">
			<DATE value="12-12-1998"/>
			<TIME value="11:15 PM"/>
		</DTREC>
    </asr_contactsection>
</asr>

<sa>
	<adminsection>
		<CCNA value="fubar"/>
		<PON value="asf123454"/>
		<ASR_NO value="1234567"/>
	</adminsection>
	<sa_circuitdetail>
		<SECTLV type="section">
			<SECTION value="-15.8T"/>
			<SECTION value="+07.OR"/>
		</SECTLV>
	</sa_circuitdetail>
	<sa_location>
	</sa_location>
	<remarks>
		<REMARKS value="These are remarks"/>
	</remarks>

</sa>
<aci>
	<adminsection>
		<CCNA value="fubar"/>
		<PON value="asf123454"/>
		<ASR_NO value="1234567"/>
	</adminsection>
	<aci_circuitdetail>
		<CKR value="fubar"/>
	</aci_circuitdetail>
</aci>

</specialaccess>
